---
# name of instances
name: argocd

# this is for argo type deployments of this chart (set to true)
ignoreHelmHooks: false

# add to this list to deploy team instances to these namespaces
namespaces:
- assemble-argocd

# operator manages upgrades
operator: 
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  sourceName: redhat-operators
  sourceNamespace: openshift-marketplace
  disableDefaultArgoCD: true

# see the TEAM_DOCS.md for more information
teamInstancesAreClusterScoped: true

# adding your secrets for git access or other repository credentials
secrets: []
# EXAMPLE ...
# secrets:
#   - name: git-auth
#     username: 'user'
#     password: 'pass1234'
#     sshPrivateKey: ''

# https://argocd-operator.readthedocs.io/en/latest/reference/argocd/
argocd_cr:
  version: v2.4.11
  applicationSet: {}
  notifications:
    enabled: true
  rbac:
    defaultPolicy: 'role:admin'
    policy: |
      g, system:cluster-admins, role:admin
    scopes: '[groups]'
  resourceExclusions: |
    - apiGroups:
        - tekton.dev
      clusters:
        - '*'
      kinds:
        - TaskRun
        - PipelineRun
  server:
    route:
      enabled: true
      tls:
        termination: reencrypt
  sso:
    dex:
      resources:
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 250m
          memory: 128Mi
      openShiftOAuth: true
    provider: dex

initialRepositories: []
  #initialRepositories:
  #  - name: redhat-cop
  #    type: helm
  #    url: https://redhat-cop.github.io/helm-charts

  # configure your repo credential template (override this)
repositoryCredentials: []
  # repositoryCredentials:
  #   - name: private-repo-creds
  #     url: https://gitlab-ce.apps.openshift-498-bd8hw.do500.redhatlabs.dev
  #     type: git
  #     password: password
  #     username: username
initialApps: []
  # initialApps:
  #   - name: init-app
  #     path: argocd/
  #     repoURL: https://gitlab-ce.apps.openshift-498-bd8hw.do500.redhatlabs.dev
  #     targetRevision: HEAD