{{- if .Values.apps.pipelines.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-pipelines-operator-rh
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/pipelines-operator
    repoURL: https://github.com/trevorbox/assemble-platforms.git
    targetRevision: gitops
  project: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
{{- end }}
