{{- if .Values.apps.rhsso.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhsso-backstage
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: backstage
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/rhsso-backstage
    repoURL: https://github.com/trevorbox/assemble-platforms.git
    targetRevision: gitops
    # TODO need to path keycloakrealm with credentials from k8s secret, potentially created from vault
    helm:
      parameters:
        keycloak:
          realm:
            identityProvider:
              clientId: "TODO"
              clientSecret: "TODO"
              enabled: "true"
        backstage:
          host: {{ .Values.apps.rhsso.backstage.host }}
  project: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
{{- end }}
