{{- if .Values.apps.rhsso.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhsso-backstage
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: backstage
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/rhsso-backstage
    repoURL: https://github.com/trevorbox/assemble-platforms.git
    targetRevision: gitops
    # TODO need to path keycloakrealm with credentials from k8s secret, potentially created from vault RE this snippet
    # keycloak:
    #   realm:
    #     identityProvider:
    #       clientId: "{{ lookup('ansible.builtin.env', 'GITHUB_CLIENT_ID') }}"
    #       clientSecret: "{{ lookup('ansible.builtin.env', 'GITHUB_CLIENT_SECRET') }}"
    #       enabled: "{{ false if lookup('ansible.builtin.env', 'GITHUB_CLIENT_SECRET') == '' else true }}" 
    # helm:
    #   valueFiles:
    #     - values-rhsso-operator.yaml
  project: default
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
{{- end }}
