keycloak:
  instances: 1
  hostname: ""
  routeName: ""
  realm:
    name: backstage
    enabled: true
    displayName: Backstage Authentication Realm
    identityProvider:
      enabled: true
      clientId: "none"
      clientSecret: "secret"
  client:
    name: backstage
    secretName: openshift-client

assemble:
  group: assemble

backstage:
  host: ""
